// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: library.proto

#include "library.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace infinity {
namespace module {
namespace library {
constexpr Library_link::Library_link(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : pitch_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , sdb_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct Library_linkDefaultTypeInternal {
  constexpr Library_linkDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~Library_linkDefaultTypeInternal() {}
  union {
    Library_link _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT Library_linkDefaultTypeInternal _Library_link_default_instance_;
constexpr Library::Library(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sdblist_()
  , sdblink_()
  , name_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , engine_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , dictionary_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , icon_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , author_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , infor_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , sdbdefault_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , eula_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , warrantdate_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , warranttime_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , imt_version_(0)
  , version_(0)
  , checkmethod_(0u)
  , autocheck_(false){}
struct LibraryDefaultTypeInternal {
  constexpr LibraryDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~LibraryDefaultTypeInternal() {}
  union {
    Library _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT LibraryDefaultTypeInternal _Library_default_instance_;
}  // namespace library
}  // namespace module
}  // namespace infinity
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_library_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_library_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_library_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_library_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library_link, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library_link, pitch_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library_link, sdb_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, imt_version_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, name_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, engine_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, dictionary_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, icon_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, author_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, version_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, infor_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, sdblist_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, sdbdefault_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, sdblink_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, checkmethod_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, autocheck_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, eula_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, warrantdate_),
  PROTOBUF_FIELD_OFFSET(::infinity::module::library::Library, warranttime_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::infinity::module::library::Library_link)},
  { 7, -1, sizeof(::infinity::module::library::Library)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::infinity::module::library::_Library_link_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::infinity::module::library::_Library_default_instance_),
};

const char descriptor_table_protodef_library_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rlibrary.proto\022\027infinity.module.library"
  "\"\357\002\n\007Library\022\023\n\013IMT_Version\030\001 \001(\001\022\014\n\004nam"
  "e\030\002 \001(\t\022\016\n\006engine\030\003 \001(\t\022\022\n\ndictionary\030\004 "
  "\001(\t\022\014\n\004icon\030\005 \001(\t\022\016\n\006author\030\006 \001(\t\022\017\n\007ver"
  "sion\030\007 \001(\001\022\r\n\005infor\030\010 \001(\t\022\017\n\007sdblist\030\t \003"
  "(\t\022\022\n\nsdbdefault\030\n \001(\t\0226\n\007sdblink\030\013 \003(\0132"
  "%.infinity.module.library.Library.link\022\023"
  "\n\013checkMethod\030\014 \001(\r\022\021\n\tautoCheck\030\r \001(\010\022\014"
  "\n\004eula\030\016 \001(\t\022\023\n\013warrantDate\030\017 \001(\t\022\023\n\013war"
  "rantTime\030\020 \001(\t\032\"\n\004link\022\r\n\005pitch\030\001 \001(\t\022\013\n"
  "\003sdb\030\002 \001(\tb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_library_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_library_2eproto = {
  false, false, 418, descriptor_table_protodef_library_2eproto, "library.proto", 
  &descriptor_table_library_2eproto_once, nullptr, 0, 2,
  schemas, file_default_instances, TableStruct_library_2eproto::offsets,
  file_level_metadata_library_2eproto, file_level_enum_descriptors_library_2eproto, file_level_service_descriptors_library_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_library_2eproto_getter() {
  return &descriptor_table_library_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_library_2eproto(&descriptor_table_library_2eproto);
namespace infinity {
namespace module {
namespace library {

// ===================================================================

class Library_link::_Internal {
 public:
};

Library_link::Library_link(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:infinity.module.library.Library.link)
}
Library_link::Library_link(const Library_link& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  pitch_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_pitch().empty()) {
    pitch_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_pitch(), 
      GetArenaForAllocation());
  }
  sdb_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sdb().empty()) {
    sdb_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sdb(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:infinity.module.library.Library.link)
}

inline void Library_link::SharedCtor() {
pitch_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
sdb_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

Library_link::~Library_link() {
  // @@protoc_insertion_point(destructor:infinity.module.library.Library.link)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Library_link::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  pitch_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sdb_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Library_link::ArenaDtor(void* object) {
  Library_link* _this = reinterpret_cast< Library_link* >(object);
  (void)_this;
}
void Library_link::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Library_link::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Library_link::Clear() {
// @@protoc_insertion_point(message_clear_start:infinity.module.library.Library.link)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  pitch_.ClearToEmpty();
  sdb_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Library_link::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string pitch = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_pitch();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.link.pitch"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string sdb = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_sdb();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.link.sdb"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Library_link::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:infinity.module.library.Library.link)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string pitch = 1;
  if (!this->_internal_pitch().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pitch().data(), static_cast<int>(this->_internal_pitch().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.link.pitch");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_pitch(), target);
  }

  // string sdb = 2;
  if (!this->_internal_sdb().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sdb().data(), static_cast<int>(this->_internal_sdb().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.link.sdb");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sdb(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:infinity.module.library.Library.link)
  return target;
}

size_t Library_link::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:infinity.module.library.Library.link)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string pitch = 1;
  if (!this->_internal_pitch().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pitch());
  }

  // string sdb = 2;
  if (!this->_internal_sdb().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sdb());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Library_link::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Library_link::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Library_link::GetClassData() const { return &_class_data_; }

void Library_link::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<Library_link *>(to)->MergeFrom(
      static_cast<const Library_link &>(from));
}


void Library_link::MergeFrom(const Library_link& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:infinity.module.library.Library.link)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_pitch().empty()) {
    _internal_set_pitch(from._internal_pitch());
  }
  if (!from._internal_sdb().empty()) {
    _internal_set_sdb(from._internal_sdb());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Library_link::CopyFrom(const Library_link& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:infinity.module.library.Library.link)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Library_link::IsInitialized() const {
  return true;
}

void Library_link::InternalSwap(Library_link* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &pitch_, GetArenaForAllocation(),
      &other->pitch_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &sdb_, GetArenaForAllocation(),
      &other->sdb_, other->GetArenaForAllocation()
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Library_link::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_library_2eproto_getter, &descriptor_table_library_2eproto_once,
      file_level_metadata_library_2eproto[0]);
}

// ===================================================================

class Library::_Internal {
 public:
};

Library::Library(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  sdblist_(arena),
  sdblink_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:infinity.module.library.Library)
}
Library::Library(const Library& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      sdblist_(from.sdblist_),
      sdblink_(from.sdblink_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArenaForAllocation());
  }
  engine_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_engine().empty()) {
    engine_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_engine(), 
      GetArenaForAllocation());
  }
  dictionary_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_dictionary().empty()) {
    dictionary_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_dictionary(), 
      GetArenaForAllocation());
  }
  icon_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_icon().empty()) {
    icon_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_icon(), 
      GetArenaForAllocation());
  }
  author_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_author().empty()) {
    author_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_author(), 
      GetArenaForAllocation());
  }
  infor_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_infor().empty()) {
    infor_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_infor(), 
      GetArenaForAllocation());
  }
  sdbdefault_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sdbdefault().empty()) {
    sdbdefault_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sdbdefault(), 
      GetArenaForAllocation());
  }
  eula_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_eula().empty()) {
    eula_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_eula(), 
      GetArenaForAllocation());
  }
  warrantdate_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_warrantdate().empty()) {
    warrantdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_warrantdate(), 
      GetArenaForAllocation());
  }
  warranttime_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_warranttime().empty()) {
    warranttime_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_warranttime(), 
      GetArenaForAllocation());
  }
  ::memcpy(&imt_version_, &from.imt_version_,
    static_cast<size_t>(reinterpret_cast<char*>(&autocheck_) -
    reinterpret_cast<char*>(&imt_version_)) + sizeof(autocheck_));
  // @@protoc_insertion_point(copy_constructor:infinity.module.library.Library)
}

inline void Library::SharedCtor() {
name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
engine_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
dictionary_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
icon_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
author_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
infor_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
sdbdefault_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
eula_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
warrantdate_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
warranttime_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&imt_version_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&autocheck_) -
    reinterpret_cast<char*>(&imt_version_)) + sizeof(autocheck_));
}

Library::~Library() {
  // @@protoc_insertion_point(destructor:infinity.module.library.Library)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Library::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  engine_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  dictionary_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  icon_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  author_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  infor_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sdbdefault_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  eula_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  warrantdate_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  warranttime_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Library::ArenaDtor(void* object) {
  Library* _this = reinterpret_cast< Library* >(object);
  (void)_this;
}
void Library::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Library::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Library::Clear() {
// @@protoc_insertion_point(message_clear_start:infinity.module.library.Library)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sdblist_.Clear();
  sdblink_.Clear();
  name_.ClearToEmpty();
  engine_.ClearToEmpty();
  dictionary_.ClearToEmpty();
  icon_.ClearToEmpty();
  author_.ClearToEmpty();
  infor_.ClearToEmpty();
  sdbdefault_.ClearToEmpty();
  eula_.ClearToEmpty();
  warrantdate_.ClearToEmpty();
  warranttime_.ClearToEmpty();
  ::memset(&imt_version_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&autocheck_) -
      reinterpret_cast<char*>(&imt_version_)) + sizeof(autocheck_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Library::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double IMT_Version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          imt_version_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string engine = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_engine();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.engine"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string dictionary = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_dictionary();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.dictionary"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string icon = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_icon();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.icon"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string author = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_author();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.author"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double version = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 57)) {
          version_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // string infor = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          auto str = _internal_mutable_infor();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.infor"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string sdblist = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_sdblist();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.sdblist"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<74>(ptr));
        } else goto handle_unusual;
        continue;
      // string sdbdefault = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          auto str = _internal_mutable_sdbdefault();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.sdbdefault"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .infinity.module.library.Library.link sdblink = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_sdblink(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<90>(ptr));
        } else goto handle_unusual;
        continue;
      // uint32 checkMethod = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 96)) {
          checkmethod_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool autoCheck = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 104)) {
          autocheck_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string eula = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 114)) {
          auto str = _internal_mutable_eula();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.eula"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string warrantDate = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 122)) {
          auto str = _internal_mutable_warrantdate();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.warrantDate"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string warrantTime = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 130)) {
          auto str = _internal_mutable_warranttime();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "infinity.module.library.Library.warrantTime"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Library::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:infinity.module.library.Library)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double IMT_Version = 1;
  if (!(this->_internal_imt_version() <= 0 && this->_internal_imt_version() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_imt_version(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name(), target);
  }

  // string engine = 3;
  if (!this->_internal_engine().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_engine().data(), static_cast<int>(this->_internal_engine().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.engine");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_engine(), target);
  }

  // string dictionary = 4;
  if (!this->_internal_dictionary().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_dictionary().data(), static_cast<int>(this->_internal_dictionary().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.dictionary");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_dictionary(), target);
  }

  // string icon = 5;
  if (!this->_internal_icon().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_icon().data(), static_cast<int>(this->_internal_icon().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.icon");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_icon(), target);
  }

  // string author = 6;
  if (!this->_internal_author().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_author().data(), static_cast<int>(this->_internal_author().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.author");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_author(), target);
  }

  // double version = 7;
  if (!(this->_internal_version() <= 0 && this->_internal_version() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(7, this->_internal_version(), target);
  }

  // string infor = 8;
  if (!this->_internal_infor().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_infor().data(), static_cast<int>(this->_internal_infor().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.infor");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_infor(), target);
  }

  // repeated string sdblist = 9;
  for (int i = 0, n = this->_internal_sdblist_size(); i < n; i++) {
    const auto& s = this->_internal_sdblist(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.sdblist");
    target = stream->WriteString(9, s, target);
  }

  // string sdbdefault = 10;
  if (!this->_internal_sdbdefault().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sdbdefault().data(), static_cast<int>(this->_internal_sdbdefault().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.sdbdefault");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_sdbdefault(), target);
  }

  // repeated .infinity.module.library.Library.link sdblink = 11;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_sdblink_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(11, this->_internal_sdblink(i), target, stream);
  }

  // uint32 checkMethod = 12;
  if (this->_internal_checkmethod() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(12, this->_internal_checkmethod(), target);
  }

  // bool autoCheck = 13;
  if (this->_internal_autocheck() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(13, this->_internal_autocheck(), target);
  }

  // string eula = 14;
  if (!this->_internal_eula().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_eula().data(), static_cast<int>(this->_internal_eula().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.eula");
    target = stream->WriteStringMaybeAliased(
        14, this->_internal_eula(), target);
  }

  // string warrantDate = 15;
  if (!this->_internal_warrantdate().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_warrantdate().data(), static_cast<int>(this->_internal_warrantdate().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.warrantDate");
    target = stream->WriteStringMaybeAliased(
        15, this->_internal_warrantdate(), target);
  }

  // string warrantTime = 16;
  if (!this->_internal_warranttime().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_warranttime().data(), static_cast<int>(this->_internal_warranttime().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "infinity.module.library.Library.warrantTime");
    target = stream->WriteStringMaybeAliased(
        16, this->_internal_warranttime(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:infinity.module.library.Library)
  return target;
}

size_t Library::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:infinity.module.library.Library)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string sdblist = 9;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(sdblist_.size());
  for (int i = 0, n = sdblist_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      sdblist_.Get(i));
  }

  // repeated .infinity.module.library.Library.link sdblink = 11;
  total_size += 1UL * this->_internal_sdblink_size();
  for (const auto& msg : this->sdblink_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string engine = 3;
  if (!this->_internal_engine().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_engine());
  }

  // string dictionary = 4;
  if (!this->_internal_dictionary().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_dictionary());
  }

  // string icon = 5;
  if (!this->_internal_icon().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_icon());
  }

  // string author = 6;
  if (!this->_internal_author().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_author());
  }

  // string infor = 8;
  if (!this->_internal_infor().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_infor());
  }

  // string sdbdefault = 10;
  if (!this->_internal_sdbdefault().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sdbdefault());
  }

  // string eula = 14;
  if (!this->_internal_eula().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_eula());
  }

  // string warrantDate = 15;
  if (!this->_internal_warrantdate().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_warrantdate());
  }

  // string warrantTime = 16;
  if (!this->_internal_warranttime().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_warranttime());
  }

  // double IMT_Version = 1;
  if (!(this->_internal_imt_version() <= 0 && this->_internal_imt_version() >= 0)) {
    total_size += 1 + 8;
  }

  // double version = 7;
  if (!(this->_internal_version() <= 0 && this->_internal_version() >= 0)) {
    total_size += 1 + 8;
  }

  // uint32 checkMethod = 12;
  if (this->_internal_checkmethod() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_checkmethod());
  }

  // bool autoCheck = 13;
  if (this->_internal_autocheck() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Library::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Library::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Library::GetClassData() const { return &_class_data_; }

void Library::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<Library *>(to)->MergeFrom(
      static_cast<const Library &>(from));
}


void Library::MergeFrom(const Library& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:infinity.module.library.Library)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  sdblist_.MergeFrom(from.sdblist_);
  sdblink_.MergeFrom(from.sdblink_);
  if (!from._internal_name().empty()) {
    _internal_set_name(from._internal_name());
  }
  if (!from._internal_engine().empty()) {
    _internal_set_engine(from._internal_engine());
  }
  if (!from._internal_dictionary().empty()) {
    _internal_set_dictionary(from._internal_dictionary());
  }
  if (!from._internal_icon().empty()) {
    _internal_set_icon(from._internal_icon());
  }
  if (!from._internal_author().empty()) {
    _internal_set_author(from._internal_author());
  }
  if (!from._internal_infor().empty()) {
    _internal_set_infor(from._internal_infor());
  }
  if (!from._internal_sdbdefault().empty()) {
    _internal_set_sdbdefault(from._internal_sdbdefault());
  }
  if (!from._internal_eula().empty()) {
    _internal_set_eula(from._internal_eula());
  }
  if (!from._internal_warrantdate().empty()) {
    _internal_set_warrantdate(from._internal_warrantdate());
  }
  if (!from._internal_warranttime().empty()) {
    _internal_set_warranttime(from._internal_warranttime());
  }
  if (!(from._internal_imt_version() <= 0 && from._internal_imt_version() >= 0)) {
    _internal_set_imt_version(from._internal_imt_version());
  }
  if (!(from._internal_version() <= 0 && from._internal_version() >= 0)) {
    _internal_set_version(from._internal_version());
  }
  if (from._internal_checkmethod() != 0) {
    _internal_set_checkmethod(from._internal_checkmethod());
  }
  if (from._internal_autocheck() != 0) {
    _internal_set_autocheck(from._internal_autocheck());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Library::CopyFrom(const Library& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:infinity.module.library.Library)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Library::IsInitialized() const {
  return true;
}

void Library::InternalSwap(Library* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  sdblist_.InternalSwap(&other->sdblist_);
  sdblink_.InternalSwap(&other->sdblink_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &name_, GetArenaForAllocation(),
      &other->name_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &engine_, GetArenaForAllocation(),
      &other->engine_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &dictionary_, GetArenaForAllocation(),
      &other->dictionary_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &icon_, GetArenaForAllocation(),
      &other->icon_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &author_, GetArenaForAllocation(),
      &other->author_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &infor_, GetArenaForAllocation(),
      &other->infor_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &sdbdefault_, GetArenaForAllocation(),
      &other->sdbdefault_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &eula_, GetArenaForAllocation(),
      &other->eula_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &warrantdate_, GetArenaForAllocation(),
      &other->warrantdate_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &warranttime_, GetArenaForAllocation(),
      &other->warranttime_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Library, autocheck_)
      + sizeof(Library::autocheck_)
      - PROTOBUF_FIELD_OFFSET(Library, imt_version_)>(
          reinterpret_cast<char*>(&imt_version_),
          reinterpret_cast<char*>(&other->imt_version_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Library::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_library_2eproto_getter, &descriptor_table_library_2eproto_once,
      file_level_metadata_library_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace library
}  // namespace module
}  // namespace infinity
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::infinity::module::library::Library_link* Arena::CreateMaybeMessage< ::infinity::module::library::Library_link >(Arena* arena) {
  return Arena::CreateMessageInternal< ::infinity::module::library::Library_link >(arena);
}
template<> PROTOBUF_NOINLINE ::infinity::module::library::Library* Arena::CreateMaybeMessage< ::infinity::module::library::Library >(Arena* arena) {
  return Arena::CreateMessageInternal< ::infinity::module::library::Library >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
